"""Model hist

Revision ID: 179350e18f71
Revises: 1d5bff473eef
Create Date: 2020-10-05 17:56:55.660686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '179350e18f71'
down_revision = '1d5bff473eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hist_weather_statiion', 'Location_name_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_weather_statiion', sa.Column('Location_name_slug', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
