"""Model

Revision ID: 1d5bff473eef
Revises: 6cea92b6307a
Create Date: 2020-10-05 16:41:02.842145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5bff473eef'
down_revision = '6cea92b6307a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hist_weather_statiion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=8), nullable=True),
    sa.Column('reception_time', sa.DateTime(), nullable=True),
    sa.Column('Location_name', sa.String(length=80), nullable=False),
    sa.Column('Location_name_slug', sa.String(length=80), nullable=False),
    sa.Column('Location_lon', sa.Float(), nullable=False),
    sa.Column('Location_lat', sa.Float(), nullable=False),
    sa.Column('id_loc', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('reference_time', sa.DateTime(), nullable=True),
    sa.Column('sunset_time', sa.DateTime(), nullable=True),
    sa.Column('sunrise_time', sa.DateTime(), nullable=True),
    sa.Column('clouds', sa.Integer(), nullable=True),
    sa.Column('rain', sa.String(length=20), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('sea_level', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('temp_kf', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('detailed_status', sa.String(length=80), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('weather_icon_name', sa.String(length=20), nullable=True),
    sa.Column('visibility_distance', sa.Integer(), nullable=True),
    sa.Column('dewpoint', sa.Float(), nullable=True),
    sa.Column('humidex', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['weather_station.station_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hist_weather_statiion')
    # ### end Alembic commands ###
