"""Model estacion metereologica cambios en formato

Revision ID: 6cea92b6307a
Revises: abd64871ca74
Create Date: 2020-10-05 14:37:04.482334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cea92b6307a'
down_revision = 'abd64871ca74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_station', 'latitud',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('weather_station', 'longitud',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_station', 'longitud',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    op.alter_column('weather_station', 'latitud',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
