"""Model estacion metereologica

Revision ID: abd64871ca74
Revises: 0acf0406ed74
Create Date: 2020-10-05 14:10:12.479402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd64871ca74'
down_revision = '0acf0406ed74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_station',
    sa.Column('station_id', sa.String(length=8), nullable=False),
    sa.Column('municipio', sa.String(length=80), nullable=False),
    sa.Column('municipio_slug', sa.String(length=80), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(length=8), nullable=False),
    sa.Column('latitud_gd', sa.Float(), nullable=False),
    sa.Column('longitud', sa.String(length=8), nullable=False),
    sa.Column('longitud_gd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('municipio_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_station')
    # ### end Alembic commands ###
